
name: OpenGL Test OSMesa

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install OSMesa
      run: |        
        sudo apt-get install libosmesa6-dev libopengl0 libglx-mesa0 libgl1-mesa-dev libglu1-mesa mesa-utils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[opengl]"

    - name: Run tests
      env:
        PYOPENGL_PLATFORM: osmesa
        LIBGL_ALWAYS_SOFTWARE: 1
      run: |
        
        #Xvfb :1 -screen 0 1024x768x24 &
        #export DISPLAY=:1
        #glxinfo | grep "OpenGL version"
        #osmesainfo

        # python src/osmesa.py
        python src/opengl_pic.py

    - name: Upload image artifact I
      uses: actions/upload-artifact@v4
      with:
        name: rendered-image-I
        path: osmesa_output.jpeg

    - name: Upload image artifact II
      uses: actions/upload-artifact@v4
      with:
        name: rendered-image-II
        path: osmesa_output.ppm
